### ISSUE TITLE
Packages Page

### ISSUE THREAD

**Issue by steffilazerte** [reconhub/recon_site_reboot#1]
### TODO

- [ ] Decide what badge status packages have and where this information is stored
- [ ] Ensure all packages have their documentation pages listed in the DESCRIPTION (i.e., outbreaks has a docs page, but since they don't list it in DESCRIPTION it isn't picked up by the R-Universe and therefore we don't have it.
- [ ] Ensure logos/hex stickers are findable (i.e. listed in the repo and labelled somewhere with "logo" or "hex").
	- [ ] Check how R-Universe reports them, if findable in the same way as pkgdown, they should be returned by the API
- [ ] Get all the packages into R-Universe collections
   - Including "Related Packages"
- [ ] #3
